### ISSUE TITLE
[PG] - Client Account: Restrict Operator Billing For A Client 

### ISSUE THREAD

**Issue by vinodtapmobi** [vinodtapmobi/havok-operations#1]
There must be a options to select which operator billing is allowed and which operator billing is not allowed for a particular client. This will be done by super user alone.

**Comment by soniyatapmobi** [comment]
1) Will add one more column in the client table in pg database by name AllowedOperator with comma separated values.
2) Only admin has the right to add and remove the operator for the particular client.
3) When the billing request to comes to pg, will check the client for the operator requested.
4) If client is registered with the operator requested, will proceed with billing
5) Otherwise will update the gateway transaction log and show the error message with Invalid Operator.

**Comment by soniyatapmobi** [comment]
1) After adding new client auto refresh is not working.
2) Need to show the list operator for the client in the grid view.
3) Need to have option for editing the list of operator for already existing client.
4) Need to give excel format for requesting to create the new client with all the details to the platform admin.
5) @saurabhtz : Please do the testing for both the restricted operator and allowed operator for the TZZ as of now.And share the all screen shot after testing here.
6) Testing billing url is http://111.93.115.200/xercesnode/Test.aspx. As of now only vodafone is blocked for TZZ Client and other operator billing will work.
7) Client should be able to see the list of operator allowed for him.

**Comment by soniyatapmobi** [comment]
1) Replace the old asp:gridview with the new generic grid view asp:GridviewEx which resolves the point 1-3.
2) Added the interface where the client can see his allowed carrier and can request for updating the carrier by sending the mail to the payment gateway admin with the new allowed carriers.
