### ISSUE TITLE
[Pl] Third party content Download & Third party content billing

### ISSUE THREAD

**Issue by saurabhtz** [vinodtapmobi/havok-operations#49]
Need to have a feature billing will happen at our end but the content download will happen at third party server.

We will have the previews on our platform but billing and download will happen at third party server. Need to maintain logs for the persons going for billing & callbacks for those customers.

**Comment by vinodtapmobi** [comment]
For each block we will provide ContentRedirectUrl and ChargingRedirectUrl property.

If ChargingRedirectUrl is not null, when a user clicks on the content in the block, we will redirect the user instead of redirecting to PG.

If ContentRedirectUrl is not null, when a user clicks on the content in the block, we will charge the user using PG and then redirect him to this url to download the content.

**Comment by vinodtapmobi** [comment]
ChargingRedirectUrl  has been implemented. We HAVE to park ContentRedirectUrl for later.

**Comment by saurabhtz** [comment]
One more change to be made billing will happen at third party end a callback will be raised to us and based on that we will initiate the download from third party.

It will be a direct download link & preview will be shared to us content partner.

Lumata requirement.
