### ISSUE TITLE
CG - Include Client Permissions while searching metadata

### ISSUE THREAD

**Issue by aravind56060** [vinodtapmobi/havok-operations#84]
We need to check whether the requested client has permission to access each metadata and return only which he has access for Search API.

In platform add ClientId in metadata dto and store its value in content set item

**Comment by soniyatapmobi** [comment]
1) Updated the search api of content gateway to provide all content of client that he has access to meaning if he has permission of accessing some other client id content then search api will return that contents also plus his contents.

2) Updated the search by content id api in the same way.

3) Updated static search api in the same way.

4) Static search api is not returning client id and we are not displaying too in the platform. In this case platform user will not be able to differentiate which content belongs to which client id.

**Comment by soniyatapmobi** [comment]
@vinodtapmobi  : Sir, Do we need to return the client id and display in the platform so it will be more visible for the platform user which content belong to which client id ?

**Comment by soniyatapmobi** [comment]
1) Static search API is now returning item including client id,content id and content type with page, page size and total items.
2) Now in static.aspx page in platform we are displaying client id also with content id and content preview so that platform user can differentiate which content belongs to which client id.
