### ISSUE TITLE
[PL] Live link not working.

### ISSUE THREAD

**Issue by saurabhtz** [vinodtapmobi/havok-operations#89]
Live link for testing the pages on handset is not working .

Error:- Object reference not set to an instance of an object.

link is :- r.tapmobi.in/r.aspx?pageid=5

**Comment by vinodtapmobi** [comment]
@soniyatapmobi  Put the reason for the error and solution to solve it.

**Comment by soniyatapmobi** [comment]
1) The issue was when we were published node, after a point of time it was throwing error " The given key is not present in the dictionary"
2) Static dictionary declared in the ControlTypeManager class was losing all its key after period of time.
3) So we were checking in the renderingservice class if controlTypes does not contain any key then we are re-initializing aging using the following line of code

```
                  if (!controlTypes.ContainsKey(entity.Group))
                      ControlTypeManager.ReInitialize(); 
```
